### ISSUE TITLE
empty mysql backups

### ISSUE THREAD

**Issue by qzaidi** [sukria/Backup-Manager#12]
If a .my.cnf file already exists, backup-manager will create an empty sql file (and a 14 byte bz2 file if compression is on). This happens because it uses the --defaults-extra-file option from mysql, and this overrides everything except the ~/.my.cnf. The failure is not reported anywhere (not even in the verbose mode).

It should not fail silently - if mysqldump failed, $PIPESTATUS could be used to determine failure.

**Comment by harmv** [comment]
this is quite a big issue... failing silently is not acceptable for any app, but especially for a backup app.

**Comment by NetJump** [comment]
Same problem over here. And it's not solved yet!!! This report is open since July the 4th of 2011! Thats quite a huge time for such a bad bug in my opinion.

backup-manager 0.7.10.1-2
Linux 3.2.0-4-amd64 #1 SMP Debian 3.2.68-1+deb7u2 x86_64 GNU/Linux

**Comment by kissifrot** [comment]
Can you try with the mentionned patch?

**Comment by NetJump** [comment]
Yep, that worked. It showed me an error this time.
BUT (Now it comes)... This is not the main problem.

My backup-manager worked fine for years now. Anytime with the same login combination and there has never changed anything.

And some weeks before the mysql backup stopped working from one day to the other. There has to be an update which is causing the main problem.

And here my suggestions what the actual problem is:
Backup-manager loads the mysql login from "/root/.backup-manager_my.cnf". In there is WRONG PASSWORD! And the wrong password is even in there wehen I delete this file and let backup-manager recreate it. So I searched and searched for a reason... And I found one... If I write the correct login into this file, everything is working very nicely. But as soon as backup-manager recreates this file, there is a wrong password in there. And I found out, that this problem is not existing if I am using a password without the "$" in it. So there is a problem in backup-manager. If the password is containing a "$", the password is not fully beeing written to the cnf file.
Example:
Password in "/etc/backup-manager.conf" file: myultra$specialpassword
Password in "/root/.backup-manager_my.cnf" file: myultra

So everything after the "$" is cut away in the "/root/.backup-manager_my.cnf" file.
Can you fix that? Or is there maybe already a fix for this?

Thank you & best regards!

**Comment by mvrueden** [comment]
I am not sure if this helps, but: 
I experienced this error when I changed the user and password to create the backups.
As mentioned above deleting the file `/root/.backup-manager_my.cnf` and re-run `backup-manager` solved the problem for me. 
In general I would very much appreciate it if backup-manager were a bit more chatty and a bit more error prone in case of exiting in such a case.

**Comment by bluemanos** [comment]
The issue happening also to me :/

I'm login as root on the server. When I'm using root mysql privileges in /etc/backup-managere.conf than the mysql dumps are ok. Any other mysql user cant create dumps - even if he have full privileges.

Second thing - every time I'm running the backup-manager, it saying that he creating the .backup-manager_my.cnf file, but it is never created.

**Comment by kissifrot** [comment]
Does the problem still occur with 0.7.11?

**Comment by yanntech** [comment]
You have a /root/.my.cnf. This .my.cnf override backup-manager config.

1- remove your .my.cnf
2- (the best) add section in your /root/.my.cnf:

```
[mysqldump]
user=<youruser>
password=<yourpassword>
```
run again backup-manager, enjoy !

**Comment by deogracia** [comment]
"asty one ...

change my root password couple of weeks ago, and wonder why I got 14byte sql.bz2 file
I totaly forgot I manualy created a ~/.my.cnf file.

Once I delete it, compressed archive got a reasaonbly size...

Thanks @yanntech and others! you save my week!

**Comment by RaspbianFrance** [comment]
Hey here, just have the same trouble on our own backup of [howtoraspberrypi.com](https://howtoraspberrypi.com).
It's finally pretty simple, simply check in your `/etc/backup-manager.conf` if you have a `$` in your password.
In this case, simply add an `\` before it, and this should fix this issue !
