### ISSUE TITLE
Upload of incremental.bin files

### ISSUE THREAD

**Issue by romainhe** [sukria/Backup-Manager#72]
Hi, 

I can't find why my incremental files are not uploaded...

I find some fix but they don't work.
I try to edit `/usr/bin/backup-manager-upload`  : 
adding `while (<$g_root_dir/*incremental*>) {
        push @{$ra_files}, $_;
    }`

Upload method is FTP and everything works fine except incremental.bin upload...

Thx for help

System is Debian Jessie

**Comment by r-berriman** [comment]
Hi romainhe,

* ftp might be in the 'ascii' mode and therefore cannot send the binary file incremental.bin
* I notice that incremental.bin file always has the permission of 600 and ownership by 'root', therefore it cannot be read by a user running ftp, only by root. 

I wonder if there is a reason for this: maybe this file is not required for the backup, it is just a local file used by backup-manager? The daily incrementals are named with a date, something like this:
     serverhostname-foldername.20161201.tar.gz

whereas there is only 1 incremental.bin for each folder.

**Can anyone provide any information about the incremental.bin file(s)?**

Security aspects:
* ftp is really not a good option these days because of security concerns, unless run over a secure connection/TLS.  scp would be better.
* push from the server being backed up to remote system is also not a good option, because an intruder to the server could trash the remote system as well. The better option is to use a 'pull' method; i.e. the remote system does scp from the machine being backed up.

**Comment by kissifrot** [comment]
Hello,

*incremental.bin is used by tar for incremental backups, so it's local-only

**Comment by r-berriman** [comment]
Thanks for that info.
So in summary, here's a suggested method to get the backups from hostA to local host:
   $ /usr/bin/rsync -avz -e "ssh me@hostA:/var/archives/*.bz2 /local/backup/folder/
   $ /usr/bin/rsync -avz -e "ssh me@hostA:/var/archives/*.md5 /local/backup/folder/
