### ISSUE TITLE
BUG : path for file backup-manager-purge is wrong in backup-manager-upload

### ISSUE THREAD

**Issue by chandon** [sukria/Backup-Manager#91]
backup-manager-upload, line 299 :

    system("/usr/bin/backup-manager-purge --ttl=$BM_ARCHIVE_TTL --files-from=$in > $out");

and line 537 : 

    system ("/usr/bin/backup-manager-purge --ttl=$BM_ARCHIVE_TTL --files-from=$filename > $out");

The path doesn't handle alternate install BIN_PREFIX configuration (for example on Debian, package install backup-manager into /usr/local/bin)

This lead to remote backup not been purged

**Comment by chandon** [comment]
changing the path solves #5

**Comment by kissifrot** [comment]
Could you try with latest version in `devel`  branch ?

**Comment by tompar28** [comment]
Hi,

Line 37 of backup-manager ("export BM_BMP_PATH=$bmp") should be removed, otherwise backup-manager-upload tries to run $BIN_PREFIX/backup-manager-purge/backup-manager-purge instead of $BIN_PREFIX/backup-manager-purge.

Deleting this line on my system made the purging of remote archives work again.
